
application:
  title: '@project.name@'
  version: '@project.version@'

bookshelf:
  title: "My Bookshelf"
  capacity: 1000
  version: "v1.0.0"

springdoc:
  api-docs:
    enabled: false

debug: false

spring:
  datasource:
    url: jdbc:postgresql://roasted-tomato.db.elephantsql.com/db_trainer
    driver-class-name: org.postgresql.Driver
    username: trainer
    password: pwTrainer
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
